name: Tests
on: [push, pull_request]
permissions: {}

jobs:
  test:
    runs-on: ubuntu-latest
    name: Unit Tests
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v4
        with:
          persist-credentials: false
      - name: Setup node
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v4
        with:
          node-version: "22"
      - run: yarn install --frozen-lockfile
      - run: yarn test
